import { CropInfo, MarketPriceItem, WeatherDay, CropDisease, InputItem } from './types';

export const CROPS_DATA: CropInfo[] = [
  {
    id: 'rice',
    name: 'ধান',
    scientificName: 'Oryza sativa',
    category: 'দানা ফসল',
    seasonTag: 'আউশ, আমন ও বোরো',
    image: '/src/rice.jpg',
    suitableSeason: 'আউশ: ১ এপ্রিল - ৩০ এপ্রিল | আমন: ১৫ জুলাই - ১৫ আগস্ট | বোরো: ১৫ ডিসেম্বর - ৩১ জানুয়ারি',
    soilType: 'দোআঁশ ও এঁটেল দোআঁশ মাটি উপযুক্ত। জমিতে ভালো পানি নিষ্কাশন ব্যবস্থা থাকা দরকার।',
    seedRate: 'প্রতি একরে ৭-৮ কেজি সুস্থ ও রোগমুক্ত বীজ।',
    fertilizerGuide: 'ইউরিয়া, টিএসপি, ডিএপি, এমওপি এবং জিপসাম সার সুষম মাত্রায় প্রয়োগ করুন। অতিরিক্ত ইউরিয়া পরিহার করুন।',
    irrigationGuide: 'জমিতে প্রয়োজন অনুযায়ী ২-৩ ইঞ্চি পানি রাখুন। অতিরিক্ত পানি দীর্ঘ সময় জমিয়ে রাখবেন না। ধান পাকার ৭-১০ দিন আগে পানি বের করে দিন।',
    commonPests: ['মাজরা পোকা', 'বাদামি গাছফড়িং (BPH)', 'পাতা মোড়ানো পোকা', 'গলমাছি'],
    commonDiseases: ['ধান ব্লাস্ট', 'ব্যাকটেরিয়াল লিফ ব্লাইট', 'শীথ ব্লাইট', 'বাদামি দাগ রোগ'],
    harvestingTime: 'শীষের প্রায় ৮০-৮৫% ধান পেকে সোনালী বা হলুদ হলে কাটাই উপযুক্ত।',
    preservation: 'ধান ভালোভাবে রোদে শুকিয়ে ১২% আর্দ্রতায় এনে শুকনা ও পরিষ্কার স্থানে বায়ুরোধী পাত্রে সংরক্ষণ করুন।',
  },
  {
    id: 'wheat',
    name: 'গম',
    scientificName: 'Triticum aestivum',
    category: 'দানা ফসল',
    seasonTag: 'রবি মৌসুম (শীতকাল)',
    image: '/src/wheat.jpg',
    suitableSeason: '১৫ নভেম্বর - ৩০ নভেম্বর (রবি মৌসুম)',
    soilType: 'উর্বর দোআঁশ ও বেলে-দোআঁশ মাটি গম চাষের জন্য সবচেয়ে ভালো।',
    seedRate: 'প্রতি একরে ৪৮-৫০ কেজি বীজ।',
    fertilizerGuide: 'ইউরিয়া, টিএসপি, এমওপি, জিপসাম এবং বোরন সার নির্দেশিত মাত্রায় প্রয়োগ করুন।',
    irrigationGuide: 'সাধারণত ৩টি সেচ প্রয়োজন: প্রথম সেচ মুকুট শিকড় গজানোর সময় (১৭-২১ দিন), দ্বিতীয় সেচ শীষ বের হওয়ার মুখে (৪৫-৫০ দিন), তৃতীয় সেচ দানা গঠনের সময় (৭০-৭৫ দিন)।',
    commonPests: ['জাব পোকা', 'ইঁদুর'],
    commonDiseases: ['গমের ব্লাস্ট', 'পাতার মরিচা রোগ', 'আলগা চিটা'],
    harvestingTime: 'গাছ ও শীষ সম্পূর্ণ হলুদ হয়ে শুকিয়ে গেলে সকালে গম কাটা উচিত।',
    preservation: 'রোদে শুকিয়ে আর্দ্রতা ১০-১২% এ এনে ঠান্ডা স্থানে সংরক্ষণ করুন।',
  },
  {
    id: 'maize',
    name: 'ভুট্টা',
    scientificName: 'Zea mays',
    category: 'দানা ফসল',
    seasonTag: 'রবি ও খরিফ মৌসুম',
    image: '/src/maize.jpg',
    suitableSeason: 'রবি মৌসুম: অক্টোবর - নভেম্বর | খরিফ মৌসুম: ফেব্রুয়ারি - মার্চ',
    soilType: 'পানি জমে না এমন গভীর উর্বর বেলে-দোআঁশ ও দোআঁশ মাটি।',
    seedRate: 'প্রতি একরে ৮-১০ কেজি হাইব্রিড ভুট্টা বীজ।',
    fertilizerGuide: 'ভুট্টায় প্রচুর খাদ্য উপাদান প্রয়োজন। ইউরিয়া, টিএসপি, পটাশ, জিপসাম এবং জিংক সালফেট প্রয়োগ আবশ্যক।',
    irrigationGuide: 'গাছের ৪-৫ পাতা বয়সে প্রথম সেচ, ৮-১০ পাতা বয়সে দ্বিতীয় সেচ, ফুল আসার সময় তৃতীয় সেচ ও দানা পুষ্ট হওয়ার সময় চতুর্থ সেচ দিন।',
    commonPests: ['ফল আর্মিওয়ার্ম', 'কাণ্ড ছিদ্রকারী পোকা'],
    commonDiseases: ['পাতার দাগ রোগ', 'কাণ্ড পচা রোগ', 'বীজ পচা রোগ'],
    harvestingTime: 'মোচার খোসা শুকিয়ে খড়ের রঙ ধারণ করলে এবং দানার গোড়ায় কালো দাগ দেখা দিলে সংগ্রহ করুন।',
    preservation: 'দানা ছাড়িয়ে ১২% আর্দ্রতায় শুকিয়ে সংরক্ষণ করুন।',
  },
  {
    id: 'potato',
    name: 'আলু',
    scientificName: 'Solanum tuberosum',
    category: 'সবজি',
    seasonTag: 'শীতকালীন প্রধান ফসল',
    image: '/src/potato.jpg',
    suitableSeason: '১ নভেম্বর - ২০ নভেম্বর (রবি মৌসুম)',
    soilType: 'হালকা বেলে দোআঁশ ও উর্বর পলি দোআঁশ মাটি আলু চাষের জন্য আদর্শ।',
    seedRate: 'প্রতি একরে ৬০০-৮০০ কেজি প্রত্যয়িত বীজ আলু।',
    fertilizerGuide: 'জৈব সারসহ ইউরিয়া, টিএসপি, পটাশ ও ম্যাগনেসিয়াম প্রয়োজন। মাটির নিচে কন্দ বৃদ্ধিতে পটাশের ভূমিকা গুরুত্বপূর্ণ।',
    irrigationGuide: 'সাধারণত ২-৩টি হালকা সেচ লাগে। আলুর গোড়ায় যেন পানি দীর্ঘক্ষণ জমে না থাকে।',
    commonPests: ['আলুর জাব পোকা', 'কাটুই পোকা'],
    commonDiseases: ['নাবী ধসা (Late Blight)', 'আগাম ধসা (Early Blight)', 'কালো পা রোগ'],
    harvestingTime: 'রোপণের ৮০-৯০ দিন পর গাছ শুকিয়ে গেলে আলু তুলতে হয়।',
    preservation: 'হিমাগারে বা শুষ্ক ঠান্ডা অন্ধকার স্থানে বাতাস চলাচলযুক্ত অবস্থায় সংরক্ষণ।',
  },
  {
    id: 'mustard',
    name: 'সরিষা',
    scientificName: 'Brassica napus',
    category: 'তৈলবীজ ও মসলা',
    seasonTag: 'স্বল্পমেয়াদী রবি ফসল',
    image: '/src/mustard.jpg',
    suitableSeason: 'অক্টোবরের শেষ থেকে নভেম্বরের মাঝামাঝি',
    soilType: 'উর্বর দোআঁশ ও পলি-দোআঁশ মাটি।',
    seedRate: 'প্রতি একরে ৩-৩.৫ কেজি সুস্থ বীজ।',
    fertilizerGuide: 'ইউরিয়া, টিএসপি, পটাশ ও সালফার (গন্ধক) সার সরিষার তেলের পরিমাণ বাড়ায়।',
    irrigationGuide: 'ফুল আসার আগে একবার (২০-২৫ দিন) এবং শুঁটি গঠনের সময় একবার (৪০-৪৫ দিন) হালকা সেচ।',
    commonPests: ['জাব পোকা (সবচেয়ে ক্ষতিকর)', 'শুঁটি ছিদ্রকারী পোকা'],
    commonDiseases: ['অল্টারনারিয়া ব্লাইট', 'ডাউনি মিলডিউ'],
    harvestingTime: 'গাছ ও শুঁটি ৭০-৮০% হলুদ হলে সকালে কাটা উচিত।',
    preservation: 'রোদে শুকিয়ে আর্দ্রতা ৮-৯% এ এনে বায়ুরোধী পাত্রে রাখা।',
  },
  {
    id: 'tomato',
    name: 'টমেটো',
    scientificName: 'Solanum lycopersicum',
    category: 'সবজি',
    seasonTag: 'শীত ও গ্রীষ্মকালীন',
    image: '/src/tomato.jpg',
    suitableSeason: 'শীতকালীন: অক্টোবর - নভেম্বর | গ্রীষ্মকালীন আগাম: মে - জুলাই (বারি হাইব্রিড-৮)',
    soilType: 'উর্বর বেলে দোআঁশ ও পলি দোআঁশ মাটি। পিএইচ (pH) ৬.০-৭.০ ও পর্যাপ্ত জৈব পদার্থ দরকার।',
    seedRate: 'প্রতি একরে ৮০-১০০ গ্রাম হাইব্রিড বীজ (চারা বানিয়ে ২৫-৩০ দিন বয়সে জমিতে রোপণ)।',
    fertilizerGuide: 'প্রতি একরে ৪-৫ টন গোবর, ১০০ কেজি ইউরিয়া, ১৫০ কেজি টিএসপি, ১০০ কেজি এমওপি এবং ২০ কেজি জিপসাম। ফুল ও ফল ধরার পর ইউরিয়া ও পটাশ উপরি প্রয়োগ করুন।',
    irrigationGuide: 'টমেটো খরা ও অতিরিক্ত পানি উভয়তেই সংবেদনশীল। প্রতি ৭-১০ দিন পর পর হালকা সেচ দিন। গোড়ায় নালা দিয়ে পানি দেওয়া উত্তম।',
    commonPests: ['সাদা মাছি (Whitefly)', 'টমেটোর ফল ছিদ্রকারী পোকা', 'জাব পোকা', 'পাতা সুড়ঙ্গকারী পোকা'],
    commonDiseases: ['নাবী ধসা (Late Blight)', 'পাতা কোঁকড়ানো ভাইরাস (Leaf Curl Virus)', 'আগাম ধসা', 'ব্যাকটেরিয়াল ঢলে পড়া'],
    harvestingTime: 'চারা রোপণের ৬০-৮০ দিন পর ফল সংগ্রহ শুরু হয়। বাজারের দূরত্ব অনুযায়ী আধা-পাকা বা পূর্ণ পাকা ফল তুলুন।',
    preservation: 'পাকা টমেটো ঠান্ডা ও ছায়াযুক্ত স্থানে ১০-১২° সে. তাপমাত্রায় ৮-১০ দিন পর্যন্ত তাজা থাকে।',
  },
  {
    id: 'brinjal',
    name: 'বেগুন',
    scientificName: 'Solanum melongena',
    category: 'সবজি',
    seasonTag: 'বারোমাসি সবজি',
    image: '/src/brinjal.jpg',
    suitableSeason: 'শীতকালীন: আগস্ট - অক্টোবর | বারোমাসি ও গ্রীষ্মকালীন: ফেব্রুয়ারি - মে',
    soilType: 'পানি জমে না এমন সুনিষ্কাশিত গভীর দোআঁশ ও এঁটেল দোআঁশ মাটি সর্বোত্তম।',
    seedRate: 'প্রতি একরে ১২০-১৫০ গ্রাম বীজ (চারা তৈরি করে ৩০-৩৫ দিন বয়সে নির্দিষ্ট দূরত্বে রোপণ)।',
    fertilizerGuide: 'জমি তৈরিতে গোবর ৫-৬ টন, ইউরিয়া ১০০ কেজি, টিএসপি ৮০ কেজি, এমওপি ৭০ কেজি, জিপসাম ২০ কেজি। ইউরিয়া ও পটাশ ৩ কিস্তিতে উপরি প্রয়োগ করুন।',
    irrigationGuide: 'শীত মৌসুমে ১০-১৫ দিন পর পর সেচ দিন। গ্রীষ্মকালে মাটি শুকিয়ে এলে ৫-৭ দিন পর পর হালকা সেচ। গোড়ায় পানি জমতে দেওয়া যাবে না।',
    commonPests: ['ডগা ও ফল ছিদ্রকারী পোকা', 'সাদা মাছি', 'লাল মাকড়', 'জাব পোকা'],
    commonDiseases: ['ব্যাকটেরিয়াল ঢলে পড়া (Bacterial Wilt)', 'ফোমোপসিস ব্লাইট ও ফল পচা', 'গোড়া পচা রোগ', 'লিটল লিফ ভাইরাস'],
    harvestingTime: 'চারা রোপণের ৬০-৭০ দিন পর বেগুন ধরা শুরু হয়। কচি ও উজ্জ্বল চকচকে থাকা অবস্থায় নিয়মিত সংগ্রহ করুন।',
    preservation: 'শীতল ও শুষ্ক স্থানে বাতাস চলাচলযুক্ত ঝুড়িতে বেগুন ৪-৫ দিন সতেজ থাকে।',
  },
  {
    id: 'cauliflower',
    name: 'ফুলকপি',
    scientificName: 'Brassica oleracea var. botrytis',
    category: 'সবজি',
    seasonTag: 'শীতকালীন ও আগাম জাত',
    image: '/src/cauliflower.jpg',
    suitableSeason: 'আগাম জাত: আগস্ট - সেপ্টেম্বর | প্রধান মৌসুম: অক্টোবর - নভেম্বর | গ্রীষ্মকালীন জাত: মে - জুন',
    soilType: 'উর্বর ও পর্যাপ্ত জৈব সার সমৃদ্ধ দোআঁশ ও পলি দোআঁশ মাটি সবচেয়ে উপযোগী।',
    seedRate: 'প্রতি একরে ১০০-১২০ গ্রাম উন্নত বীজ। ২৫-৩০ দিনের সুস্থ চারা সারি ৬০ সেমি ও চারা ৪৫ সেমি দূরত্বে রোপণ।',
    fertilizerGuide: 'প্রতি একরে ৪-৫ টন গোবর, ১০০ কেজি ইউরিয়া, ৮০ কেজি টিএসপি, ৮০ কেজি এমওপি এবং ৫ কেজি বোরাক্স সার অপরিহার্য (বোরনের অভাবে বাদামি পচন হয়)।',
    irrigationGuide: 'মাটিতে রসের অভাব হলে ফুল ছোট ও আঁটসাঁটহীন হয়। রোপণের পর হালকা সেচ দিন এবং এরপর ৮-১০ দিন পর পর পরিমিত সেচ দিন।',
    commonPests: ['ফুলকপির লেদা পোকা (Prodenia)', 'হীরা পিঠ মথ (DBM)', 'জাব পোকা'],
    commonDiseases: ['অল্টারনারিয়া ব্লাইট (পাতার দাগ)', 'কালো পচা (Black rot)', 'হুইপটেল রোগ', 'বাদামি পচন (Brown rot)'],
    harvestingTime: 'চারা রোপণের ৬০-৭৫ দিন পর ফুল নিরেট ও উজ্জ্বল সাদা থাকা অবস্থায় পাতা সহ কেটে তুলুন।',
    preservation: 'ঠান্ডা ও আর্দ্র স্থানে সংরক্ষণ করলে ফুলকপি ৭-১০ দিন সতেজ থাকে।',
  },
  {
    id: 'papaya',
    name: 'পেঁপে',
    scientificName: 'Carica papaya',
    category: 'ফল ও অর্থকরী',
    seasonTag: 'বারোমাসি ফল ও পুষ্টিকর সবজি',
    image: '/src/papaya.jpg',
    suitableSeason: 'বছরের যেকোনো সময়ে রোপণ সম্ভব; তবে সেপ্টেম্বর-অক্টোবর এবং ফেব্রুয়ারি-মার্চ চারা রোপণের শ্রেষ্ঠ সময়।',
    soilType: 'উঁচু ও মাঝারি উঁচু বেলে-দোআঁশ মাটি। পেঁপে গাছ জলাবদ্ধতা একদম সহ্য করতে পারে না, ড্রেন অপরিহার্য।',
    seedRate: 'প্রতি একরে ২০০-২৫০ গ্রাম বীজ (অথবা প্রায় ১,০০০-১,২০০টি সুস্থ পলিব্যাগ চারা)।',
    fertilizerGuide: 'প্রতিটি গর্তে ১০ কেজি পচা গোবর, ৫০০ গ্রাম টিএসপি, ৫০০ গ্রাম পটাশ, ২৫০ গ্রাম জিপসাম ও ৫০ গ্রাম বোরন সার। প্রতি ২ মাস পর পর ইউরিয়া ও পটাশ উপরি দিন।',
    irrigationGuide: 'শুষ্ক মৌসুমে প্রতি ৭-১০ দিন পর পর নালার মাধ্যমে সেচ দিন। বর্ষাকালে গাছের গোড়ায় পানি জমলে দ্রুত নিষ্কাশন করুন।',
    commonPests: ['মিলিবাগ (দই পোকা)', 'সাদা মাছি', 'মাকড় (Mites)'],
    commonDiseases: ['পেঁপের রিং স্পট ভাইরাস (PRSV)', 'গোড়া ও শিকড় পচা রোগ (Foot rot)', 'অ্যানথ্রাকনোজ (ফল পচা)'],
    harvestingTime: 'চারা লাগানোর ৩-৪ মাস পর থেকে কাঁচা সবজি পেঁপে এবং ৯-১০ মাস পর থেকে পাকা ফল সংগ্রহ করা যায়।',
    preservation: 'কাঁচা পেঁপে স্বাভাবিক তাপমাত্রায় ১০-১২ দিন এবং পাকা পেঁপে ঠান্ডা স্থানে ৫-৭ দিন রাখা যায়।',
  },
  {
    id: 'banana',
    name: 'কলা',
    scientificName: 'Musa acuminata',
    category: 'ফল ও অর্থকরী',
    seasonTag: 'বারোমাসি অর্থকরী ফল',
    image: '/src/banana.jpg',
    suitableSeason: 'বছরে তিন মৌসুমে চারা লাগানো যায়: আশ্বিন-কার্তিক (অক্টোবর-নভেম্বর), মাঘ-ফাল্গুন (ফেব্রুয়ারি-মার্চ) ও জ্যৈষ্ঠ-আষাঢ় (মে-জুন)।',
    soilType: 'উর্বর, গভীর, সুনিষ্কাশিত পলল দোআঁশ ও এঁটেল দোআঁশ মাটি কলা চাষের জন্য সেরা।',
    seedRate: 'প্রতি একরে সুস্থ তলোয়ার সাকার (Sword sucker) প্রায় ১,২০০-১,৪০০টি (২ মি. x ২ মি. দূরত্বে)।',
    fertilizerGuide: 'প্রতি গাছে ১৫-২০ কেজি পচা গোবর, ৫০০ গ্রাম ইউরিয়া, ৪০০ গ্রাম টিএসপি, ৬০০ গ্রাম এমওপি এবং ১০০ গ্রাম জিপসাম। সার ৪-৫ কিস্তিতে উপরি প্রয়োগ করুন।',
    irrigationGuide: 'কলা গাছে প্রচুর পানি প্রয়োজন। খরা মৌসুমে ১০-১২ দিন পর পর সেচ দিন এবং বৃষ্টির পানি নিষ্কাশনে গভীর নালা রাখুন।',
    commonPests: ['কলা গাছের পাতা ও ফল বিটল পোকা', 'কলার কন্দ উইভিল', 'থ্রিপস পোকা'],
    commonDiseases: ['সিগাটোকা রোগ (Black / Yellow Sigatoka)', 'পানামা রোগ (Fusarium wilt)', 'গুচ্ছ মাথা ভাইরাস (Bunchy top)'],
    harvestingTime: 'চারা লাগানোর ১১-১৩ মাস পর মোচা থেকে কলা পুষ্ট হয়। কলার খাঁজগুলো গোলাকার রূপ নিলে কাঁদি কাটুন।',
    preservation: 'ছায়াযুক্ত ঠান্ডা ও বাতাসযুক্ত স্থানে কাঁদি ঝুলিয়ে রাখলে কলা প্রাকৃতিকভাবে সুন্দর পাকে।',
  },
  {
    id: 'betel',
    name: 'পান',
    scientificName: 'Piper betle',
    category: 'ফল ও অর্থকরী',
    seasonTag: 'বারোমাসি অর্থকরী বরোজ',
    image: '/src/betel.jpg',
    suitableSeason: 'বছরের যেকোনো সময় তবে মে-জুলাই মাস বরোজ তৈরির জন্য সেরা।',
    soilType: 'উঁচু ও মাঝারি উঁচু ছায়াযুক্ত বেলে-দোআঁশ মাটি। জল নিষ্কাশন অত্যন্ত জরুরি।',
    seedRate: 'প্রতি বরোজে প্রায় ১০,০০০-১২,০০০ লতা কাটিং।',
    fertilizerGuide: 'সরিষার খৈল, পচা গোবর ও অল্প মাত্রায় টিএসপি সার অত্যন্ত উপকারী।',
    irrigationGuide: 'বরোজে পর্যাপ্ত আর্দ্রতা রাখতে হালকা স্প্রিংকলার বা ঝাঝরি দিয়ে সেচ দিন। পানি জমতে দেওয়া যাবে না।',
    commonPests: ['পানের সাদামাছি', 'থ্রিপস পোকা'],
    commonDiseases: ['গোড়া পচা (ফুট রট)', 'পাতা পোড়া রোগ'],
    harvestingTime: 'রোপণের ৫-৬ মাস পর থেকে নিয়মিত পাতা সংগ্রহ করা যায়।',
    preservation: 'ভেজা ছালা বা কলাপাতা দিয়ে জড়িয়ে ঠান্ডা ঘরে পান তাজা রাখা হয়।',
  },
];

export const INITIAL_MARKET_PRICES: MarketPriceItem[] = [
  {
    id: '1',
    name: 'ধান',
    category: 'ধান',
    price: 1500,
    unit: 'টাকা/মণ',
    location: 'ঢাকা',
    change: 'up',
    changePercentage: 3.2,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ১০:০০',
  },
  {
    id: '2',
    name: 'আলু',
    category: 'সবজি',
    price: 20,
    unit: 'টাকা/কেজি',
    location: 'ঢাকা',
    change: 'down',
    changePercentage: 2.1,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ১০:০০',
  },
  {
    id: '3',
    name: 'টমেটো',
    category: 'সবজি',
    price: 70,
    unit: 'টাকা/কেজি',
    location: 'ঢাকা',
    change: 'up',
    changePercentage: 5.4,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৯:৩০',
  },
  {
    id: '4',
    name: 'আম',
    category: 'ফল',
    price: 40,
    unit: 'টাকা/কেজি',
    location: 'ঢাকা',
    change: 'stable',
    changePercentage: 0,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৯:১৫',
  },
  {
    id: '5',
    name: 'গম',
    category: 'গম',
    price: 1450,
    unit: 'টাকা/মণ',
    location: 'ঢাকা',
    change: 'up',
    changePercentage: 1.8,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৮:৪৫',
  },
  {
    id: '6',
    name: 'মরিচ (কাঁচা)',
    category: 'মসলা',
    price: 110,
    unit: 'টাকা/কেজি',
    location: 'ঢাকা',
    change: 'down',
    changePercentage: 4.5,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৯:০০',
  },
];

export const INITIAL_WEATHER_DAYS: WeatherDay[] = [
  { dayName: 'আজ', date: '৪ সেপ্টেম্বর', temp: 32, condition: 'মেঘলা', humidity: 60, rainProbability: 80, warning: 'ভারী বৃষ্টির সম্ভাবনা' },
  { dayName: 'দিন ১', date: '৫ সেপ্টেম্বর', temp: 31, condition: 'বৃষ্টি', humidity: 65, rainProbability: 85, warning: 'ভারী বৃষ্টি সতর্কতা' },
  { dayName: 'দিন ২', date: '৬ সেপ্টেম্বর', temp: 30, condition: 'বৃষ্টি', humidity: 68, rainProbability: 80, warning: 'মাঝারি বৃষ্টি' },
  { dayName: 'দিন ৩', date: '৭ সেপ্টেম্বর', temp: 31, condition: 'হালকা বৃষ্টি', humidity: 62, rainProbability: 60 },
  { dayName: 'দিন ৪', date: '৮ সেপ্টেম্বর', temp: 32, condition: 'আংশিক মেঘলা', humidity: 58, rainProbability: 30 },
  { dayName: 'দিন ৫', date: '৯ সেপ্টেম্বর', temp: 33, condition: 'রৌদ্রোজ্জ্বল', humidity: 55, rainProbability: 15 },
  { dayName: 'দিন ৬', date: '১০ সেপ্টেম্বর', temp: 33, condition: 'রৌদ্রোজ্জ্বল', humidity: 52, rainProbability: 10 },
];

export const INITIAL_DISEASE: CropDisease = {
  id: 'rice-blast',
  crop: 'ধান',
  name: 'ধানের ব্লাস্ট রোগ (Rice Blast)',
  description: 'ধানের ব্লাস্ট একটি ছত্রাকজনিত মারাত্মক রোগ। পাতা, গিঁট ও শীষে আক্রমণ করে এবং বেশি হলে ফলন উল্লেখযোগ্যভাবে কমে যেতে পারে।',
  symptoms: [
    'পাতায় চোখের মতো বাদামি দাগ দেখা যায়।',
    'দাগের মাঝখান ধূসর/সাদা হতে পারে।',
    'শীষের গিঁটে কালচে বা বাদামি দাগ হয়।',
    'আক্রান্ত শীষ শুকিয়ে যেতে পারে।',
    'বেশি আক্রমণে ধানের ফলন উল্লেখযোগ্যভাবে কমে যায়।',
  ],
  organicSolution: 'আক্রান্ত অংশের পাতা কেটে পুড়িয়ে ফেলা। সকালে কাঠের ছাই গাছে ছিটানো এবং জমিতে সুষম জৈব সার প্রয়োগ।',
  chemicalSolution: {
    chemical: 'ট্রাইসাইক্লাজল 76% WP (Tricyclazole 76% WP)',
    usage: 'ধানের ব্লাস্ট রোগ নিয়ন্ত্রণে',
    dose: 'পণ্যের লেবেল অনুযায়ী অথবা স্থানীয় কৃষি কর্মকর্তার পরামর্শ অনুযায়ী প্রতি লিটার পানিতে ০.৭৫ গ্রাম মিশিয়ে বিকেলে স্প্রে করুন।',
  },
  prevention: 'রোগমুক্ত প্রত্যয়িত বীজ শোধন করে বপন করুন। অতিরিক্ত ইউরিয়া সার পরিহার করে পরিমিত পটাশ ও সিলিকন সার ব্যবহার করুন।',
  image: 'https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?w=600&auto=format&fit=crop&q=80',
};

export const INITIAL_INPUT_ITEMS: InputItem[] = [
  { id: '1', category: 'ছত্রাকনাশক', name: 'tricyclazole 76% WP', quantity: 1, unit: 'প্যাকেট', price: 400, date: '4 September, 2026', selected: true },
  { id: '2', category: 'ছত্রাকনাশক', name: 'Mancozeb 75 % WP', quantity: 2, unit: 'প্যাকেট', price: 350, date: '4 September, 2026', selected: true },
  { id: '3', category: 'ছত্রাকনাশক', name: 'Carbendazim 50% WP', quantity: 1, unit: 'প্যাকেট', price: 280, date: '4 September, 2026', selected: true },
  { id: '4', category: 'সার', name: 'ইউরিয়া (Urea)', quantity: 50, unit: 'কেজি', price: 1350, date: '1 September, 2026', selected: false },
  { id: '5', category: 'সার', name: 'টিএসপি (TSP)', quantity: 25, unit: 'কেজি', price: 1100, date: '1 September, 2026', selected: false },
  { id: '6', category: 'বীজ', name: 'BRRI ধান ২৮ বীজ', quantity: 8, unit: 'কেজি', price: 640, date: '28 August, 2026', selected: false },
];

export const INITIAL_NOTIFICATIONS = [
  { id: 'n1', text: 'আজ আপনার এলাকায় ভারী বৃষ্টির সম্ভাবনা, ফসলের সুরক্ষার ব্যবস্থা নিন', type: 'weather', unread: true },
  { id: 'n2', text: 'আপনার জমিতে সেচ দেওয়ার উপযুক্ত সময় হয়েছে', type: 'task', unread: true },
  { id: 'n3', text: 'ফসলের বর্তমান বৃদ্ধি অনুযায়ী সার প্রয়োগ করুন', type: 'task', unread: false },
  { id: 'n4', text: 'আপনার এলাকায় রোগ বা পোকার আক্রমণের ঝুঁকি বেড়েছে', type: 'alert', unread: false },
  { id: 'n5', text: 'আজকের বাজারে আপনার ফসলের দাম পরিবর্তন হয়েছে', type: 'market', unread: false },
  { id: 'n6', text: 'আজকের বিশেষ টিপস—সকালে বা বিকেলে সেচ দিলে পানির অপচয় কম হয়', type: 'tip', unread: false },
];
